package org.ssm.app.pvp.utils;

public final class SampleAlumniData {

	public static final String SAMPLE_DATA = "[\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 16:59:57\",\r\n"
			+ "            \"STUDENT_NAME\": \"Thandra Naveen\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9959277572\",\r\n"
			+ "            \"EMAIL_ID\": \"thandranaveen572@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"10/25/95\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Vidyaranya Avasa Vidyalayam, Chokkaramnagar Rampur\",\r\n"
			+ "            \"SCHOOL_ID\": \"779\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2011\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"ADDRESS\": \"Bazarhathnoor\",\r\n"
			+ "            \"CITY\": \"Adilabad\",\r\n"
			+ "            \"PINCODE\": \"504304\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:05:06\",\r\n"
			+ "            \"STUDENT_NAME\": \"Gopi gangadhar\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"8899915359\",\r\n"
			+ "            \"EMAIL_ID\": \"gopugangadhar44@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/5/89\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Bazar Hathnoor\",\r\n"
			+ "            \"SCHOOL_ID\": \"829\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1999\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Defence\",\r\n"
			+ "            \"JOB LOCATION\": \"Srinagar \",\r\n"
			+ "            \"ADDRESS\": \"Bazarhathnnor (postal ) Bazarhathnnor (DI) Adilabad  (Pincod) 504304\",\r\n"
			+ "            \"CITY\": \"Adilabad\",\r\n"
			+ "            \"PINCODE\": \"504304\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:14:25\",\r\n"
			+ "            \"STUDENT_NAME\": \"Asriram\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9908380776\",\r\n"
			+ "            \"EMAIL_ID\": \"sriramallemwar@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"4/11/21\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Subhadra Nilayam,Bhainsa\",\r\n"
			+ "            \"SCHOOL_ID\": \"752\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"IX\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2006\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Administrative Services\",\r\n"
			+ "            \"JOB LOCATION\": \"No\",\r\n"
			+ "            \"ADDRESS\": \"Ganeshnagar\",\r\n"
			+ "            \"CITY\": \"Nirmal\",\r\n"
			+ "            \"PINCODE\": \"504103\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:17:22\",\r\n"
			+ "            \"STUDENT_NAME\": \"Gampa Ravinder \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"7995640726\",\r\n"
			+ "            \"EMAIL_ID\": \"ravindergampa5@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/19/68\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1983\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Government Service\",\r\n"
			+ "            \"JOB LOCATION\": \"Karimnagar \",\r\n"
			+ "            \"ADDRESS\": \"8-4-222/1,Ganeshnagar, karimnagar \",\r\n"
			+ "            \"CITY\": \"Karimnagar \",\r\n"
			+ "            \"PINCODE\": \"505001\",\r\n"
			+ "            \"COUNTRY\": \"India \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:23:55\",\r\n"
			+ "            \"STUDENT_NAME\": \"P Deepa\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"8555853946\",\r\n"
			+ "            \"EMAIL_ID\": \"deepapamukuntla@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/19/90\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VII\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2002\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Engineer\",\r\n"
			+ "            \"JOB LOCATION\": \"Mahabubnagar\",\r\n"
			+ "            \"ADDRESS\": \"HNo 1-8/3 Kondareddypally (v), Vangur (M)\",\r\n"
			+ "            \"CITY\": \"Kalwakurthy \",\r\n"
			+ "            \"PINCODE\": \"509324\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:27:50\",\r\n"
			+ "            \"STUDENT_NAME\": \"Mallaram Srinivas Reddy\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9989170630\",\r\n"
			+ "            \"EMAIL_ID\": \"malathisrinu@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/1/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1984\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Assistant ProfessorCommerce\",\r\n"
			+ "            \"ADDRESS\": \"5-6-301, Maruthimagar\",\r\n"
			+ "            \"CITY\": \"Karimnagar\",\r\n"
			+ "            \"PINCODE\": \"506001\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:46:44\",\r\n"
			+ "            \"STUDENT_NAME\": \"CHATLA THARUN\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"7287966069\",\r\n"
			+ "            \"EMAIL_ID\": \"chatlatharun126@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/12/00\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Bazar Hathnoor\",\r\n"
			+ "            \"SCHOOL_ID\": \"829\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VII\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2013\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"JOB LOCATION\": \"NIZAMABAD\",\r\n"
			+ "            \"ADDRESS\": \"Bazarhatnoor 1-47 dist Adilabad\",\r\n"
			+ "            \"CITY\": \"Adilabad\",\r\n"
			+ "            \"PINCODE\": \"504304\",\r\n"
			+ "            \"COUNTRY\": \"India \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 17:54:13\",\r\n"
			+ "            \"STUDENT_NAME\": \"RAMAVATH.SHIVA\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9573861582\",\r\n"
			+ "            \"EMAIL_ID\": \"ramavatht98@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/10/01\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2017\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Nurse\",\r\n"
			+ "            \"JOB LOCATION\": \"DINDI\",\r\n"
			+ "            \"ADDRESS\": \"AYYAVAREPALLI ACHAMPET\",\r\n"
			+ "            \"CITY\": \"ACHAMPET\",\r\n"
			+ "            \"PINCODE\": \"509375\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 18:10:21\",\r\n"
			+ "            \"STUDENT_NAME\": \"Gujja Sateesh \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9440071066\",\r\n"
			+ "            \"EMAIL_ID\": \"sateesh.gujja@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"1/4/73\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Manthani\",\r\n"
			+ "            \"SCHOOL_ID\": \"743\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1988\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Lawyer\",\r\n"
			+ "            \"JOB LOCATION\": \"Karimnagar \",\r\n"
			+ "            \"ADDRESS\": \"10-3-324/23, flat no 502, Himalaya Nivas, vidyanagar karimnagar \",\r\n"
			+ "            \"CITY\": \"Karimnagar \",\r\n"
			+ "            \"PINCODE\": \"505001\",\r\n"
			+ "            \"COUNTRY\": \"India \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 18:13:57\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kande charithasri\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9912420959\",\r\n"
			+ "            \"EMAIL_ID\": \"charithasri.1234@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/17/06\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VII\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2017\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Volunteer\",\r\n"
			+ "            \"JOB LOCATION\": \"Kalwakurthy\",\r\n"
			+ "            \"ADDRESS\": \"Indiranagar 2-57/5\\r\\nKalwakurthy\\r\\nNagar kurnool\",\r\n"
			+ "            \"CITY\": \"Kalwakurthy\",\r\n"
			+ "            \"PINCODE\": \"509324\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 18:38:17\",\r\n"
			+ "            \"STUDENT_NAME\": \"Srinivas Ravula\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9820914234\",\r\n"
			+ "            \"EMAIL_ID\": \"srini3925@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"11/15/74\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1989\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Engineer\",\r\n"
			+ "            \"JOB LOCATION\": \"Mumbai\",\r\n"
			+ "            \"ADDRESS\": \"A-902, Arihant Abhilasha, Plot No.10, Sector 35H, Kharghar \",\r\n"
			+ "            \"CITY\": \"Navi Mumbai\",\r\n"
			+ "            \"PINCODE\": \"410210\",\r\n"
			+ "            \"COUNTRY\": \"India \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 19:00:22\",\r\n"
			+ "            \"STUDENT_NAME\": \"Bandi Sampath Kumar \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9885584756\",\r\n"
			+ "            \"EMAIL_ID\": \"bsk2_b4u@yahoo.co.in\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/30/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1984\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Professor\",\r\n"
			+ "            \"JOB LOCATION\": \"Karimnagar \",\r\n"
			+ "            \"ADDRESS\": \"H.No. 2-10-1525 ,Jyothi Nagar, Karimnagar \",\r\n"
			+ "            \"CITY\": \"Karimnagar \",\r\n"
			+ "            \"PINCODE\": \"505001\",\r\n"
			+ "            \"COUNTRY\": \"India \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 19:07:11\",\r\n"
			+ "            \"STUDENT_NAME\": \"GADE HARIKRISHNA\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"09963648487\",\r\n"
			+ "            \"EMAIL_ID\": \"gade69@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"4/14/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1983\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Karimnagar\",\r\n"
			+ "            \"ADDRESS\": \"H.no. 1-5-245, padmashali street, near: barath talkies.\",\r\n"
			+ "            \"CITY\": \"Karimnagar\",\r\n"
			+ "            \"PINCODE\": \"505001\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 19:11:13\",\r\n"
			+ "            \"STUDENT_NAME\": \"Tamatam kishore goud\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9705867215\",\r\n"
			+ "            \"EMAIL_ID\": \"kishoregoudtamatam@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"3/13/98\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2014\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"JOB LOCATION\": \"Studant\",\r\n"
			+ "            \"ADDRESS\": \"Kalwakurthy indhiranagar \",\r\n"
			+ "            \"CITY\": \"Kalwakurthy\",\r\n"
			+ "            \"PINCODE\": \"509324\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 19:12:00\",\r\n"
			+ "            \"STUDENT_NAME\": \"Ramesh Suddala\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9394474776\",\r\n"
			+ "            \"EMAIL_ID\": \"suddalaramesh@yahoo.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/15/68\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1984\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"KARIMNAGAR \",\r\n"
			+ "            \"ADDRESS\": \"#2-10-167,JYOTHINAGAR,KARIMNAGAR-505001\",\r\n"
			+ "            \"CITY\": \"KARIMNAGAR \",\r\n"
			+ "            \"PINCODE\": \"505001\",\r\n"
			+ "            \"COUNTRY\": \"Bharath (INDIA) \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 19:20:03\",\r\n"
			+ "            \"STUDENT_NAME\": \"Myadam Abhilash\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"8142576346\",\r\n"
			+ "            \"EMAIL_ID\": \"abhilashmyadam04@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/4/00\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir High School, Narayanpet\",\r\n"
			+ "            \"SCHOOL_ID\": \"772\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2015\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad\",\r\n"
			+ "            \"ADDRESS\": \"3-557,jajapur,Narayanpet, Mahabubnagar, Telangana,509210\",\r\n"
			+ "            \"CITY\": \"Hyderabad\",\r\n"
			+ "            \"PINCODE\": \"509210\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 20:05:08\",\r\n"
			+ "            \"STUDENT_NAME\": \"Srinivas Donapati\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9900235156\",\r\n"
			+ "            \"EMAIL_ID\": \"srinu1104@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"11/4/81\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, LMD colony, Thimmapur Mandal, Karimnagar\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1997\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Engineer\",\r\n"
			+ "            \"JOB LOCATION\": \"Bangalore\",\r\n"
			+ "            \"ADDRESS\": \"H No 8 29 Mahathma nagar LMD colony karimnagar\",\r\n"
			+ "            \"CITY\": \"Karimnagar \",\r\n"
			+ "            \"PINCODE\": \"505527\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 20:22:05\",\r\n"
			+ "            \"STUDENT_NAME\": \"Katam Tejaswini\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9491257061\",\r\n"
			+ "            \"EMAIL_ID\": \"tejaswini.katam5@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"5/5/97\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir High School, Peddapally\",\r\n"
			+ "            \"SCHOOL_ID\": \"744\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2012\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"JOB LOCATION\": \"Sulthanabad\",\r\n"
			+ "            \"ADDRESS\": \"Sulthanabad\",\r\n"
			+ "            \"CITY\": \"Sulthanabad\",\r\n"
			+ "            \"PINCODE\": \"505185\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 20:31:46\",\r\n"
			+ "            \"STUDENT_NAME\": \"Sainath gandham\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"09866828425\",\r\n"
			+ "            \"EMAIL_ID\": \"gandham.sai81@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/17/81\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kisangally, Bhainsa\",\r\n"
			+ "            \"SCHOOL_ID\": \"753\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1996\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Bhainsa\",\r\n"
			+ "            \"ADDRESS\": \"Rajeev Nagar bhainsa\",\r\n"
			+ "            \"CITY\": \"Bhainsa\",\r\n"
			+ "            \"PINCODE\": \"504103\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 20:37:56\",\r\n"
			+ "            \"STUDENT_NAME\": \"Boidi Abhishek\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9701522664\",\r\n"
			+ "            \"EMAIL_ID\": \"abhi.boidi@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"5/5/89\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kubeer\",\r\n"
			+ "            \"SCHOOL_ID\": \"757\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2000\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Farmer\",\r\n"
			+ "            \"JOB LOCATION\": \"Kubeer\",\r\n"
			+ "            \"ADDRESS\": \"H.no: 6-122; opposite post office; Main Road; Post &mandal: Kubeer; District Nirmal; Telangana; Pincode:504103\",\r\n"
			+ "            \"CITY\": \"Kubeer\",\r\n"
			+ "            \"PINCODE\": \"504103\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 21:12:24\",\r\n"
			+ "            \"STUDENT_NAME\": \"Anuga. Malathi \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"7981136169\",\r\n"
			+ "            \"EMAIL_ID\": \"malathi34@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"4/15/72\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1981\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Housewife\",\r\n"
			+ "            \"JOB LOCATION\": \"Housewife \",\r\n"
			+ "            \"ADDRESS\": \"Padmacolony, nallakunta, Hyderabad \",\r\n"
			+ "            \"CITY\": \"Nallakunta,Hyderabad\",\r\n"
			+ "            \"PINCODE\": \"500044\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 21:21:40\",\r\n"
			+ "            \"STUDENT_NAME\": \"Deepthi sadhu\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9441367084\",\r\n"
			+ "            \"EMAIL_ID\": \"muralidharreddysadhu@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/28/91\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2007\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"IT Professional\",\r\n"
			+ "            \"JOB LOCATION\": \"USA\",\r\n"
			+ "            \"ADDRESS\": \"H-no 7-108,Gandhinagar,Kalwakurthi. Pin code  509324\",\r\n"
			+ "            \"CITY\": \"Kalwakurthi \",\r\n"
			+ "            \"PINCODE\": \"509324\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 21:29:11\",\r\n"
			+ "            \"STUDENT_NAME\": \"Spoorthi sadhu\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9441367084\",\r\n"
			+ "            \"EMAIL_ID\": \"muralidharreddysadhu@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/20/92\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2008\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"IT Professional\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad \",\r\n"
			+ "            \"ADDRESS\": \"H-No 7-109,Gandhinagar\",\r\n"
			+ "            \"CITY\": \"Kalwakurthi \",\r\n"
			+ "            \"PINCODE\": \"509324\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 22:00:53\",\r\n"
			+ "            \"STUDENT_NAME\": \"Raja Tadvai\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9866434282\",\r\n"
			+ "            \"EMAIL_ID\": \"mail2tadvai@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/9/72\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VIII\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1986\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Global \",\r\n"
			+ "            \"ADDRESS\": \"2-7-1193\",\r\n"
			+ "            \"CITY\": \"Waddepalli \",\r\n"
			+ "            \"PINCODE\": \"506370\",\r\n"
			+ "            \"COUNTRY\": \"Indian \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 22:16:22\",\r\n"
			+ "            \"STUDENT_NAME\": \"Dr Madan Mohan Reddy\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"8500281111\",\r\n"
			+ "            \"EMAIL_ID\": \"snehanrpt@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/8/70\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir High School, Narayanpet\",\r\n"
			+ "            \"SCHOOL_ID\": \"772\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1981\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Doctor\",\r\n"
			+ "            \"JOB LOCATION\": \"Narayanpet\",\r\n"
			+ "            \"ADDRESS\": \"1-5-2,\\r\\nSneha Hospital,\\r\\nNarayanpet\",\r\n"
			+ "            \"CITY\": \"Narayanpet\",\r\n"
			+ "            \"PINCODE\": \"509210\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 22:37:51\",\r\n"
			+ "            \"STUDENT_NAME\": \"ANIL KUMAR\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9030787487\",\r\n"
			+ "            \"EMAIL_ID\": \"tally.vasudha@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"3/18/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"IX\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1983\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Auditor\",\r\n"
			+ "            \"JOB LOCATION\": \"Warangal\",\r\n"
			+ "            \"ADDRESS\": \"H no. 13-1-103, SVN Road, Warangal\",\r\n"
			+ "            \"CITY\": \"warangal\",\r\n"
			+ "            \"PINCODE\": \"506002\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 22:51:35\",\r\n"
			+ "            \"STUDENT_NAME\": \"Saiprakash\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9849134414\",\r\n"
			+ "            \"EMAIL_ID\": \"saiprakash0409@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"2/9/85\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir High School, Bandameedipally, Mahabubnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"790\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2000\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad\",\r\n"
			+ "            \"ADDRESS\": \"Plot no 190 road no 14 Durga Nagar karmanghat Hyderabad\",\r\n"
			+ "            \"CITY\": \"Hyderabad\",\r\n"
			+ "            \"PINCODE\": \"500079\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 22:51:48\",\r\n"
			+ "            \"STUDENT_NAME\": \"R.M.N.JYOTHI\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9849985600\",\r\n"
			+ "            \"EMAIL_ID\": \"rudrarajujyothivasu@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"10/8/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Vidya Mandir, Sri Nagar Colony, Kesavanagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"814\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1984\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Housewife\",\r\n"
			+ "            \"ADDRESS\": \"Flat no.506, Padmarekha Apts, jayanthi nagar, near Rajeev Nagar'X Road \",\r\n"
			+ "            \"CITY\": \"Hyderabad\",\r\n"
			+ "            \"PINCODE\": \"500045\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/20/2021 23:45:48\",\r\n"
			+ "            \"STUDENT_NAME\": \"Peddi Mallikarjun \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9849505572\",\r\n"
			+ "            \"EMAIL_ID\": \"peddi.mallikarjun@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"3/16/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1984\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"ADDRESS\": \"2-10-1475/A,Jyothinagar\",\r\n"
			+ "            \"CITY\": \"Karimnagar \",\r\n"
			+ "            \"PINCODE\": \"505001\",\r\n"
			+ "            \"COUNTRY\": \"India \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 0:11:39\",\r\n"
			+ "            \"STUDENT_NAME\": \"Thirupathi Reddy\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9491879669\",\r\n"
			+ "            \"EMAIL_ID\": \"thiru54.cool@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/31/89\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Sarawathi Shishu Mandir, Kotakonda\",\r\n"
			+ "            \"SCHOOL_ID\": \"795\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1998\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Government Service\",\r\n"
			+ "            \"JOB LOCATION\": \"Marikal\",\r\n"
			+ "            \"ADDRESS\": \"H no 4-51 thirumala pur, Narayan pet 509210\",\r\n"
			+ "            \"CITY\": \"Narayanpet\",\r\n"
			+ "            \"PINCODE\": \"509351\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 3:14:53\",\r\n"
			+ "            \"STUDENT_NAME\": \"Prathyoosha Hade\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9966643703\",\r\n"
			+ "            \"EMAIL_ID\": \"prathyoosha.g5@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"3/26/90\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Kalwakurthy\",\r\n"
			+ "            \"SCHOOL_ID\": \"761\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2005\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Housewife\",\r\n"
			+ "            \"ADDRESS\": \"H.no 6-56/3, Gandhi Nager, Kalwakurthy \",\r\n"
			+ "            \"CITY\": \"Kalwakurthy \",\r\n"
			+ "            \"PINCODE\": \"509324\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 4:26:13\",\r\n"
			+ "            \"STUDENT_NAME\": \"Rajesh D\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9012218133\",\r\n"
			+ "            \"EMAIL_ID\": \"rajeshd1908@yahoo.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"1/14/73\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Ramakrishna Vidyalayam, Khammam\",\r\n"
			+ "            \"SCHOOL_ID\": \"783\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1988\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"IT Professional\",\r\n"
			+ "            \"ADDRESS\": \"1200 Bramble Dr\",\r\n"
			+ "            \"CITY\": \"Breinigsville\",\r\n"
			+ "            \"PINCODE\": \"18031\",\r\n"
			+ "            \"COUNTRY\": \"USA\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 5:54:09\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kavali rajkumar\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9052097435\",\r\n"
			+ "            \"EMAIL_ID\": \"rajkumar.kavali@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/25/91\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"Graduation\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2007\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Rangareddy\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"Indian\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 7:22:41\",\r\n"
			+ "            \"STUDENT_NAME\": \"Aitha Anil Kumar\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9030787487\",\r\n"
			+ "            \"EMAIL_ID\": \"tally.vasudha@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"3/18/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"IX\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1983\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Auditor\",\r\n"
			+ "            \"JOB LOCATION\": \"Warangal\",\r\n"
			+ "            \"ADDRESS\": \"13-1-103, SVN Road, Warangal\",\r\n"
			+ "            \"CITY\": \"warangal\",\r\n"
			+ "            \"PINCODE\": \"506002\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 8:04:23\",\r\n"
			+ "            \"STUDENT_NAME\": \"YACHAM ARUN KUMAR\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9959890500\",\r\n"
			+ "            \"EMAIL_ID\": \"aruny.axis@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/10/92\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2006\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Chevella\",\r\n"
			+ "            \"ADDRESS\": \"H no 1-98 Chevella Ranga Reddy dist\",\r\n"
			+ "            \"CITY\": \"Chevella\",\r\n"
			+ "            \"PINCODE\": \"501503\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 8:09:09\",\r\n"
			+ "            \"STUDENT_NAME\": \"M abhinav\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"7013436356\",\r\n"
			+ "            \"EMAIL_ID\": \"luckey220f@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/23/02\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2011\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shadnagar\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 8:12:01\",\r\n"
			+ "            \"STUDENT_NAME\": \"Niranjan Kumar\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9666222561\",\r\n"
			+ "            \"EMAIL_ID\": \"niranjankumar68@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/5/85\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir, Chandulal Bharadari\",\r\n"
			+ "            \"SCHOOL_ID\": \"781\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"III\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1993\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Politician\",\r\n"
			+ "            \"ADDRESS\": \"19-1-549, Doodh Bowli, Bahadurpura\",\r\n"
			+ "            \"CITY\": \"Hyderabad\",\r\n"
			+ "            \"PINCODE\": \"500064\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:15:27\",\r\n"
			+ "            \"STUDENT_NAME\": \"Sonaila Narendar\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9989792750\",\r\n"
			+ "            \"EMAIL_ID\": \"sonailanarender@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"4/25/89\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2004\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad .villeage \",\r\n"
			+ "            \"CITY\": \"Hyderabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"Hyderabad\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:23:24\",\r\n"
			+ "            \"STUDENT_NAME\": \"Ashwini \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9959751972\",\r\n"
			+ "            \"EMAIL_ID\": \"ashwinireddy2199@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/7/21\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2010\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Housewife\",\r\n"
			+ "            \"JOB LOCATION\": \"House wife\",\r\n"
			+ "            \"ADDRESS\": \"Bandlaguda jagir \",\r\n"
			+ "            \"CITY\": \"Bandlaguda \",\r\n"
			+ "            \"PINCODE\": \"500086\",\r\n"
			+ "            \"COUNTRY\": \"INDIA\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:33:53\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kottinti vijayasri\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9848504411\",\r\n"
			+ "            \"EMAIL_ID\": \"vijayasri@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"1/2/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Sardar Nagar\",\r\n"
			+ "            \"ADDRESS\": \"D No.4-39\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:36:54\",\r\n"
			+ "            \"STUDENT_NAME\": \"Konadur Bhapgavi\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9642258208\",\r\n"
			+ "            \"EMAIL_ID\": \"bhargavi@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/7/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Housewife\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:47:54\",\r\n"
			+ "            \"STUDENT_NAME\": \"Machanpalli Harish\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9949143863\",\r\n"
			+ "            \"EMAIL_ID\": \"harishm@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/7/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:52:36\",\r\n"
			+ "            \"STUDENT_NAME\": \"Tammali Anil\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9985234456\",\r\n"
			+ "            \"EMAIL_ID\": \"anil.tammali1987@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/21/97\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VII\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2000\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 9:56:58\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kammari Raju\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9866963607\",\r\n"
			+ "            \"EMAIL_ID\": \"Rajukammari2009@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/2/87\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1997\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:01:17\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kammari Chandra Shekar\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9666455030\",\r\n"
			+ "            \"EMAIL_ID\": \"chandu_mittu@yahoo.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/6/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:04:25\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kavali Giriprasad\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9030349489\",\r\n"
			+ "            \"EMAIL_ID\": \"giriprasadk@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/2/85\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Shadnagar\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:05:11\",\r\n"
			+ "            \"STUDENT_NAME\": \"M.MAHENDER GOUD\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9848182359\",\r\n"
			+ "            \"EMAIL_ID\": \"mahigoud2359@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/26/89\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VII\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2001\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Bangalore\",\r\n"
			+ "            \"ADDRESS\": \"H.no.2-83,Aspallyguda Village,Shabazz Mandam\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:07:10\",\r\n"
			+ "            \"STUDENT_NAME\": \"Sonnayila Hanmanth\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"7780142961\",\r\n"
			+ "            \"EMAIL_ID\": \"hanmanths@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/11/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Labour\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:12:31\",\r\n"
			+ "            \"STUDENT_NAME\": \"Bobbili Naveen\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"+13125438658\",\r\n"
			+ "            \"EMAIL_ID\": \"naveenbobbili@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/21/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"IT Professional\",\r\n"
			+ "            \"JOB LOCATION\": \"U.S.A.\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:15:10\",\r\n"
			+ "            \"STUDENT_NAME\": \"Gubba Anand\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9985889253\",\r\n"
			+ "            \"EMAIL_ID\": \"anandgubba@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"5/16/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:17:55\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kuturu Narsimulu\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9052058158\",\r\n"
			+ "            \"EMAIL_ID\": \"narsimuluk@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/8/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:20:24\",\r\n"
			+ "            \"STUDENT_NAME\": \"SHIVAKUMAR MADDI\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"8309063661\",\r\n"
			+ "            \"EMAIL_ID\": \"shivanu7570@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"10/12/69\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Karimnagar\",\r\n"
			+ "            \"SCHOOL_ID\": \"805\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1984\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Government Service\",\r\n"
			+ "            \"JOB LOCATION\": \"HYDERABAD\",\r\n"
			+ "            \"ADDRESS\": \"1-4-879/49/201, SAI JYOTHI PALACE, GANDHINAGAR, HYDERABAD\",\r\n"
			+ "            \"CITY\": \"HYDERABAD\",\r\n"
			+ "            \"PINCODE\": \"500080\",\r\n"
			+ "            \"COUNTRY\": \"INDIA\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:25:10\",\r\n"
			+ "            \"STUDENT_NAME\": \"S.Madhu goud\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9949428182\",\r\n"
			+ "            \"EMAIL_ID\": \"s.madhugoud@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"1/28/82\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir , High School - Sangaredy\",\r\n"
			+ "            \"SCHOOL_ID\": \"722\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1997\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Journalist\",\r\n"
			+ "            \"JOB LOCATION\": \"Sangareddy\",\r\n"
			+ "            \"ADDRESS\": \"H.no 1-65,flat no 303, sri sai construction,near hanuman temple, pothireddypalli , sangareddy 502295\",\r\n"
			+ "            \"CITY\": \"Sangareddy\",\r\n"
			+ "            \"PINCODE\": \"502295\",\r\n"
			+ "            \"COUNTRY\": \"Bharath\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:52:27\",\r\n"
			+ "            \"STUDENT_NAME\": \"Uppu srinivas\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9866163872\",\r\n"
			+ "            \"EMAIL_ID\": \"usrinivas872@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"11/11/80\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1991\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"News Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:55:04\",\r\n"
			+ "            \"STUDENT_NAME\": \"Machanpalli Harish\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9949143963\",\r\n"
			+ "            \"EMAIL_ID\": \"harishm@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/5/83\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 10:58:21\",\r\n"
			+ "            \"STUDENT_NAME\": \"Mangali Murali Mohan\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9912623883\",\r\n"
			+ "            \"EMAIL_ID\": \"muralim@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/1/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Shankarpalli \",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:00:11\",\r\n"
			+ "            \"STUDENT_NAME\": \"Laggishetty Annapurna \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9652361746\",\r\n"
			+ "            \"EMAIL_ID\": \"laggishettyrishikesh@gamil.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"2/3/80\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1991\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Teacher\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad holi spirit school  \",\r\n"
			+ "            \"ADDRESS\": \"Vi bhonagiripally m shabad RRdist\",\r\n"
			+ "            \"CITY\": \"shabad \",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"INDIA \",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:01:48\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kamisetti pandurangam\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9703255693\",\r\n"
			+ "            \"EMAIL_ID\": \"pandukamisetti@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"6/6/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:01:55\",\r\n"
			+ "            \"STUDENT_NAME\": \"P jaganmohan\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"6281356204\",\r\n"
			+ "            \"EMAIL_ID\": \"jaganmudhiraj07@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"5/10/95\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2010\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"ADDRESS\": \"Shabad \",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:02:05\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kuthurugopal \",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9849340137\",\r\n"
			+ "            \"EMAIL_ID\": \"kuthurugopal005@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"2/2/82\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"IV\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1990\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Agriculture Professional\",\r\n"
			+ "            \"JOB LOCATION\": \"Malla Reddy Guda\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Ranga reddy\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:04:40\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kotta Vasudeva Reddy\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9866862923\",\r\n"
			+ "            \"EMAIL_ID\": \"vasudevkotta@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/21/94\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"JOB LOCATION\": \"Sitarampur\",\r\n"
			+ "            \"ADDRESS\": \"Shabad (MDL)\",\r\n"
			+ "            \"CITY\": \"R.R.dist\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:07:37\",\r\n"
			+ "            \"STUDENT_NAME\": \"Chokkampeta Naresh\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9703281143\",\r\n"
			+ "            \"EMAIL_ID\": \"nareshch@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/5/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"IT Professional\",\r\n"
			+ "            \"JOB LOCATION\": \"Jaheerabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:11:09\",\r\n"
			+ "            \"STUDENT_NAME\": \"Nalappuram venkat Reddy\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9010559933\",\r\n"
			+ "            \"EMAIL_ID\": \"venkatreddyn@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/2/84\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"VI\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1995\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Farmer\",\r\n"
			+ "            \"JOB LOCATION\": \"Shankarpalli guda\",\r\n"
			+ "            \"ADDRESS\": \"Shabad,(MDL)\",\r\n"
			+ "            \"CITY\": \"Rangareddy (Dist)\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:14:42\",\r\n"
			+ "            \"STUDENT_NAME\": \"Machamini Srikanth\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"8790694769\",\r\n"
			+ "            \"EMAIL_ID\": \"mskanth93@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"8/12/93\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1999\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Student\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:17:46\",\r\n"
			+ "            \"STUDENT_NAME\": \"Lambadi Ramu\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9703301078\",\r\n"
			+ "            \"EMAIL_ID\": \"ramu1078@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/14/93\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"IX\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1998\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Politician\",\r\n"
			+ "            \"JOB LOCATION\": \"Shabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:24:30\",\r\n"
			+ "            \"STUDENT_NAME\": \"Aerrolla Rajender Goud\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9573674242\",\r\n"
			+ "            \"EMAIL_ID\": \"rajender4u76@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/16/87\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1997\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Private Sector\",\r\n"
			+ "            \"JOB LOCATION\": \"Hyderabad\",\r\n"
			+ "            \"ADDRESS\": \"Shabad\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:31:21\",\r\n"
			+ "            \"STUDENT_NAME\": \"Yasa chakradhar Reddy\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9963272709\",\r\n"
			+ "            \"EMAIL_ID\": \"chakradarreddy444@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"7/21/88\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"V\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"1998\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Panchyat\",\r\n"
			+ "            \"JOB LOCATION\": \"Vikarabad\",\r\n"
			+ "            \"ADDRESS\": \"Aremisamma\",\r\n"
			+ "            \"CITY\": \"Shabad\",\r\n"
			+ "            \"PINCODE\": \"Shabad\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"Timestamp\": \"7/21/2021 11:34:07\",\r\n"
			+ "            \"STUDENT_NAME\": \"Kotla Hanmanth\",\r\n"
			+ "            \"STUDENT_CONTACT_NUMBER\": \"9581912439\",\r\n"
			+ "            \"EMAIL_ID\": \"kotlahanmanth420@gmail.com\",\r\n"
			+ "            \"DATE_OF_BIRTH\": \"9/8/91\",\r\n"
			+ "            \"SCHOOL_NAMES\": \"Sri Saraswathi Shishu Mandir Shabad\",\r\n"
			+ "            \"SCHOOL_ID\": \"731\",\r\n"
			+ "            \"HIGHEST_PASSOUT_CLASS\": \"X\",\r\n"
			+ "            \"PASSOUT_YEAR\": \"2007\",\r\n"
			+ "            \"CURRENT PROFESSION\": \"Businessperson\",\r\n"
			+ "            \"ADDRESS\": \"Bobbiligama village shabad mandal\",\r\n"
			+ "            \"PINCODE\": \"509217\",\r\n"
			+ "            \"COUNTRY\": \"India\",\r\n"
			+ "            \"STATE\": \"Telangana\"\r\n"
			+ "        }"
			+ "    ]";
}
